### ISSUE TITLE
Can't find gem on Rubygems

### ISSUE THREAD

**Issue by Flcn** [algolia/chronos-api#1]
https://rubygems.org/search?utf8=✓&query=chronos

**Comment by redox** [comment]
Yeah, this library is still in very alpha so we didn't published it to Rubygems. Do you mind giving it a try using a `github: 'algolia/chronos-api'` dependency?

**Comment by aspring** [comment]
Would it be possible to get this gem cut?  Looking to include this in another gem and need to be able to bring it in via .gemspec.

**Comment by redox** [comment]
I've just released that beta version on rubygems using `0.0.1`. If you want to contribute to the project, I would be very happy to merge your PR :)
