### ISSUE TITLE
cannot load such file -- chronos

### ISSUE THREAD

**Issue by bkarstaedt** [algolia/chronos-api#3]
I get the error `cannot load such file -- chronos` when I try to use this gem.

In the Gemfile I have:

```
gem 'chronos-api', github: 'algolia/chronos-api', require: 'chronos'
```

I tried with ruby 1.9.3 and 2.2.3 with not difference. I can see that RVM downloaded the gems contents correctly. Currently I have no clue why it's not working.

Do you have any ideas why this is happening?

**Comment by redox** [comment]
Hi @bkarstaedt,

I've just published a 0.0.1 version of the gem to rubygems. However, it's really beta and we're not using it anymore (Chronos wasn't the perfect fit for our needs). If you want to contribute, I would be happy to merge your PRs!
